package exceptionstudy

/*
class MyClass {
    fun myMethod(div : Int) {
        val a = 1 / div
    }
}

fun myFunction() {
    val c = MyClass()
    c.myMethod(0)
}

fun main(args : Array<String>) {
    myFunction()
}
*/